package clientecomthread;

import Pacotao.Administrador;
import Pacotao.Pessoa;
import static clientecomthread.Principal.Saida;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class Cad_Administradores extends javax.swing.JFrame {

    /**
     * Creates new form Pessoas
     */
    public Cad_Administradores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLCadNome = new javax.swing.JLabel();
        jTFCadEmail = new javax.swing.JTextField();
        jLCadDataNasc = new javax.swing.JLabel();
        jLCadCPF = new javax.swing.JLabel();
        jLCadRG = new javax.swing.JLabel();
        jLCadTel = new javax.swing.JLabel();
        jLCadEmail = new javax.swing.JLabel();
        jTFCadNome = new javax.swing.JTextField();
        jTFCadDataNasc = new javax.swing.JTextField();
        jTFCadCPF = new javax.swing.JTextField();
        jTFCadRG = new javax.swing.JTextField();
        jTFCadTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBCadCad = new javax.swing.JButton();
        jBCadCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTFCadDDD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFSenha = new javax.swing.JTextField();
        jBVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLCadNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadNome.setText("Nome:");

        jLCadDataNasc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadDataNasc.setText("Data de Nascimento:");

        jLCadCPF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadCPF.setText("CPF:");

        jLCadRG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadRG.setText("RG:");

        jLCadTel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadTel.setText("Telefone:");

        jLCadEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadEmail.setText("E-mail:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("CADASTRO ADMINISTRADOR");

        jBCadCad.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBCadCad.setText("Cadastrar");
        jBCadCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadCadActionPerformed(evt);
            }
        });

        jBCadCancelar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBCadCancelar.setText("Cancelar");
        jBCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DDD");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Login");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Senha");

        jBVoltar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBCadCad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCadCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBVoltar)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCadEmail)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTFCadDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLCadNome)
                                        .addComponent(jLCadDataNasc)
                                        .addComponent(jLCadCPF)
                                        .addComponent(jLCadRG)
                                        .addComponent(jLCadTel))
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFCadDataNasc)
                                        .addComponent(jTFCadCPF)
                                        .addComponent(jTFCadRG)
                                        .addComponent(jTFCadTel)
                                        .addComponent(jTFCadNome, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(118, 118, 118)
                                .addComponent(jTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBVoltar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadNome)
                    .addComponent(jTFCadNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadDataNasc)
                    .addComponent(jTFCadDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadCPF)
                    .addComponent(jTFCadCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadRG)
                    .addComponent(jTFCadRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadTel)
                    .addComponent(jTFCadTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFCadDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadEmail)
                    .addComponent(jTFCadEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadCad)
                    .addComponent(jBCadCancelar))
                .addGap(285, 285, 285))
        );

        setSize(new java.awt.Dimension(668, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadCancelarActionPerformed
        // TODO add your handling code here:
        limpacampos();
    }//GEN-LAST:event_jBCadCancelarActionPerformed

    private void jBCadCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadCadActionPerformed

        String nome = jTFCadNome.getText();
        String data_nasc = jTFCadDataNasc.getText();
        String CPF = jTFCadCPF.getText();
        String RG = jTFCadRG.getText();
        int telefone = (Integer.parseInt(jTFCadTel.getText()));
        int ddd = (Integer.parseInt(jTFCadDDD.getText()));
        String email = jTFCadEmail.getText();
        String login = jTFLogin.getText();
        String senha = jTFSenha.getText();
        Administrador a = new Administrador(nome, data_nasc, telefone, ddd, email, login, senha, RG, CPF);

        try {
            Principal.Saida.writeObject(14);
            Principal.Saida.writeObject(a);

        } catch (IOException ex) {
            Logger.getLogger(Cad_Administradores.class.getName()).log(Level.SEVERE, null, ex);
        }

        limpacampos();

    }//GEN-LAST:event_jBCadCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Administradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadCad;
    private javax.swing.JButton jBCadCancelar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLCadCPF;
    private javax.swing.JLabel jLCadDataNasc;
    private javax.swing.JLabel jLCadEmail;
    private javax.swing.JLabel jLCadNome;
    private javax.swing.JLabel jLCadRG;
    private javax.swing.JLabel jLCadTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFCadCPF;
    private javax.swing.JTextField jTFCadDDD;
    private javax.swing.JTextField jTFCadDataNasc;
    private javax.swing.JTextField jTFCadEmail;
    private javax.swing.JTextField jTFCadNome;
    private javax.swing.JTextField jTFCadRG;
    private javax.swing.JTextField jTFCadTel;
    private javax.swing.JTextField jTFLogin;
    private javax.swing.JTextField jTFSenha;
    // End of variables declaration//GEN-END:variables
    public void limpacampos() {
        jTFCadNome.setText("");
        jTFCadDDD.setText("");
        jTFCadCPF.setText("");
        jTFCadRG.setText("");
        jTFCadTel.setText("");
        jTFCadDataNasc.setText("");
        jTFCadEmail.setText("");
        jTFLogin.setText("");
        jTFSenha.setText("");
    }
}
