/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientecomthread;

import Pacotao.Administrador;
import static clientecomthread.Login.Entrada;
import static clientecomthread.Login.Saida;
import java.awt.Color;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Edi_Administradores extends javax.swing.JFrame {

    public Edi_Administradores() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCadCancelar = new javax.swing.JButton();
        jLCadRG = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLCadTel = new javax.swing.JLabel();
        jTFCadDDD = new javax.swing.JTextField();
        jLCadEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFCadNome = new javax.swing.JTextField();
        jTFLogin = new javax.swing.JTextField();
        jTFCadDataNasc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFCadCPF = new javax.swing.JTextField();
        jTFSenha = new javax.swing.JTextField();
        jTFCadRG = new javax.swing.JTextField();
        jLCadNome = new javax.swing.JLabel();
        jTFCadTel = new javax.swing.JTextField();
        jTFCadEmail = new javax.swing.JTextField();
        jLCadDataNasc = new javax.swing.JLabel();
        jBCadCad = new javax.swing.JButton();
        jLCadCPF = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBEdiCancelar = new javax.swing.JButton();
        jLCadRG1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLCadTel1 = new javax.swing.JLabel();
        jTFEdiDDD = new javax.swing.JTextField();
        jLCadEmail1 = new javax.swing.JLabel();
        jTFEdiNome = new javax.swing.JTextField();
        jTFEdiDataNasc = new javax.swing.JTextField();
        jTFEdiCPF = new javax.swing.JTextField();
        jTFEdiRG = new javax.swing.JTextField();
        jLCadNome1 = new javax.swing.JLabel();
        jTFEdiTel = new javax.swing.JTextField();
        jTFEdiEmail = new javax.swing.JTextField();
        jLCadDataNasc1 = new javax.swing.JLabel();
        jBEdi = new javax.swing.JButton();
        jLCadCPF1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBEdiVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEdiTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLCadNome2 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();

        jBCadCancelar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBCadCancelar.setText("Cancelar");
        jBCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadCancelarActionPerformed(evt);
            }
        });

        jLCadRG.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadRG.setText("RG:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DDD");

        jLCadTel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadTel.setText("Telefone:");

        jLCadEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadEmail.setText("E-mail:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Login");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Senha");

        jLCadNome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadNome.setText("Nome:");

        jLCadDataNasc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadDataNasc.setText("Data de Nascimento:");

        jBCadCad.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBCadCad.setText("Cadastrar");
        jBCadCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadCadActionPerformed(evt);
            }
        });

        jLCadCPF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadCPF.setText("CPF:");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Logo.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBEdiCancelar.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBEdiCancelar.setText("Cancelar");
        jBEdiCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEdiCancelarActionPerformed(evt);
            }
        });

        jLCadRG1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadRG1.setText("RG:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("DDD");

        jLCadTel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadTel1.setText("Telefone:");

        jTFEdiDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEdiDDDActionPerformed(evt);
            }
        });

        jLCadEmail1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadEmail1.setText("E-mail:");

        jLCadNome1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadNome1.setText("Nome:");

        jLCadDataNasc1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadDataNasc1.setText("Data de Nascimento:");

        jBEdi.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jBEdi.setText("Salvar");
        jBEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEdiActionPerformed(evt);
            }
        });

        jLCadCPF1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadCPF1.setText("CPF:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("EDITAR ADMINISTRADORES");

        jBEdiVoltar.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jBEdiVoltar.setText("Voltar");
        jBEdiVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEdiVoltarActionPerformed(evt);
            }
        });

        jEdiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Data de Nascimento", "CPF", "RG", "Telefone", "DDD", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jEdiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEdiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jEdiTable);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Logo.png")); // NOI18N

        jLCadNome2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLCadNome2.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(277, 277, 277)
                        .addComponent(jBEdiVoltar)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBEdi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEdiCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCadNome1)
                            .addComponent(jLCadDataNasc1)
                            .addComponent(jLCadCPF1)
                            .addComponent(jLCadRG1)
                            .addComponent(jLCadTel1)
                            .addComponent(jLabel5)
                            .addComponent(jLCadEmail1)
                            .addComponent(jLCadNome2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFEdiCPF)
                            .addComponent(jTFEdiRG)
                            .addComponent(jTFEdiTel)
                            .addComponent(jTFEdiEmail)
                            .addComponent(jTFEdiDDD)
                            .addComponent(jTFEdiDataNasc)
                            .addComponent(jTFEdiNome, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                            .addComponent(jTFId))))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBEdiVoltar)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCadNome2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadNome1)
                    .addComponent(jTFEdiNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadDataNasc1)
                    .addComponent(jTFEdiDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadCPF1)
                    .addComponent(jTFEdiCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadRG1)
                    .addComponent(jTFEdiRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCadTel1)
                    .addComponent(jTFEdiTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTFEdiDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEdiEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCadEmail1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEdi)
                    .addComponent(jBEdiCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBCadCancelarActionPerformed

    private void jBCadCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadCadActionPerformed
      
    }//GEN-LAST:event_jBCadCadActionPerformed

    private void jBEdiCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEdiCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBEdiCancelarActionPerformed

    private void jBEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEdiActionPerformed
            int id = Integer.parseInt(jTFId.getText());
            String nome = jTFEdiNome.getText();
            String data_nasc = jTFEdiDataNasc.getText();
            String CPF = jTFEdiCPF.getText();
            String RG = jTFEdiRG.getText();
            int telefone = Integer.parseInt(jTFEdiTel.getText());
            int ddd = (Integer.parseInt(jTFEdiDDD.getText()));
            String email = jTFEdiEmail.getText();
            String login = jTFLogin.getText();
            String senha = jTFSenha.getText();
            Administrador meuAdministrador = new Administrador(id, nome,data_nasc, telefone, ddd, email, login, senha, RG, CPF);
            try {
                Login.Saida.writeObject(16);
                Login.Saida.writeObject(meuAdministrador);
                carregaLista();
                
            }   catch (IOException ex) {
                    Logger.getLogger(Edi_Administradores.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jBEdiActionPerformed

    private void jEdiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEdiTableMouseClicked
        int p = jEdiTable.getSelectedRow(); // pegar a linha selecionada
        jTFId.setText((String.valueOf(jEdiTable.getValueAt(p, 0))));
        jTFEdiNome.setText((String) jEdiTable.getValueAt(p, 1)); // colocar no campor nome o que a pessoa esta selecionando
        jTFEdiDataNasc.setText((String) jEdiTable.getValueAt(p, 2));
        jTFEdiCPF.setText((String) jEdiTable.getValueAt(p, 3));
        jTFEdiRG.setText((String) jEdiTable.getValueAt(p, 4));
        jTFEdiTel.setText((String.valueOf(jEdiTable.getValueAt(p, 5))));
        jTFEdiDDD.setText((String.valueOf( jEdiTable.getValueAt(p, 6))));
        jTFEdiEmail.setText((String) jEdiTable.getValueAt(p, 7));
       
        
    }//GEN-LAST:event_jEdiTableMouseClicked
    public void carregaLista(){
        try {
            Saida.writeObject(17);//avisa que quer a lista
            LinkedList <Administrador> ListaAdmin = new LinkedList();
            ListaAdmin = (LinkedList<Administrador>) Entrada.readObject();
            DefaultTableModel table = (DefaultTableModel) jEdiTable.getModel();
            table.setNumRows(0);
            jTFId.setEnabled(false);
            
            for (int x = 0; x < ListaAdmin.size(); x++) {
               
                table.addRow(new Object[]{ListaAdmin.get(x).getId(),ListaAdmin.get(x).getNome(), ListaAdmin.get(x).getData_nasc(), ListaAdmin.get(x).getCPF(), ListaAdmin.get(x).getRG(), ListaAdmin.get(x).getTelefone(), ListaAdmin.get(x).getDdd(), ListaAdmin.get(x).getEmail()});
        
            }
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println("Erro "+ex);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregaLista();
    }//GEN-LAST:event_formWindowOpened

    private void jBEdiVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEdiVoltarActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBEdiVoltarActionPerformed

    private void jTFEdiDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEdiDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEdiDDDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edi_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edi_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edi_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edi_Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edi_Administradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadCad;
    private javax.swing.JButton jBCadCancelar;
    private javax.swing.JButton jBEdi;
    private javax.swing.JButton jBEdiCancelar;
    private javax.swing.JButton jBEdiVoltar;
    private javax.swing.JTable jEdiTable;
    private javax.swing.JLabel jLCadCPF;
    private javax.swing.JLabel jLCadCPF1;
    private javax.swing.JLabel jLCadDataNasc;
    private javax.swing.JLabel jLCadDataNasc1;
    private javax.swing.JLabel jLCadEmail;
    private javax.swing.JLabel jLCadEmail1;
    private javax.swing.JLabel jLCadNome;
    private javax.swing.JLabel jLCadNome1;
    private javax.swing.JLabel jLCadNome2;
    private javax.swing.JLabel jLCadRG;
    private javax.swing.JLabel jLCadRG1;
    private javax.swing.JLabel jLCadTel;
    private javax.swing.JLabel jLCadTel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCadCPF;
    private javax.swing.JTextField jTFCadDDD;
    private javax.swing.JTextField jTFCadDataNasc;
    private javax.swing.JTextField jTFCadEmail;
    private javax.swing.JTextField jTFCadNome;
    private javax.swing.JTextField jTFCadRG;
    private javax.swing.JTextField jTFCadTel;
    private javax.swing.JTextField jTFEdiCPF;
    private javax.swing.JTextField jTFEdiDDD;
    private javax.swing.JTextField jTFEdiDataNasc;
    private javax.swing.JTextField jTFEdiEmail;
    private javax.swing.JTextField jTFEdiNome;
    private javax.swing.JTextField jTFEdiRG;
    private javax.swing.JTextField jTFEdiTel;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFLogin;
    private javax.swing.JTextField jTFSenha;
    // End of variables declaration//GEN-END:variables
 public void limpacampos(){
         jTFCadNome.setText("");
         jTFCadDDD.setText("");
         jTFCadCPF.setText("");
         jTFCadRG.setText("");
         jTFCadTel.setText("");
         jTFCadDDD.setText("");
         jTFCadEmail.setText("");
         
    }
}
