package clientecomthread;

import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;


public class Principal extends javax.swing.JFrame {
    public static Socket conexaoSocket;
    public static ObjectOutputStream Saida;
    public static ObjectInputStream Entrada;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jBPessoas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBProduto = new javax.swing.JButton();
        jBProdutor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBEdiProdutores = new javax.swing.JButton();
        jBEdiProdutos = new javax.swing.JButton();
        jBCad_Programa = new javax.swing.JButton();
        jBCad_Entregas = new javax.swing.JButton();
        jBRelatorio = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Logo.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jBPessoas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBPessoas.setText("Cadastro Administradores");
        jBPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPessoasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("MENU");

        jBProduto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBProduto.setText("Cadastro Produto");
        jBProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProdutoActionPerformed(evt);
            }
        });

        jBProdutor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBProdutor.setText("Cadastro Produtor");
        jBProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProdutorActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Editar Administradores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBEdiProdutores.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBEdiProdutores.setText("Editar Produtores");
        jBEdiProdutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEdiProdutoresActionPerformed(evt);
            }
        });

        jBEdiProdutos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBEdiProdutos.setText("Editar Produtos");
        jBEdiProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEdiProdutosActionPerformed(evt);
            }
        });

        jBCad_Programa.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBCad_Programa.setText("Cadastro de Programas");
        jBCad_Programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCad_ProgramaActionPerformed(evt);
            }
        });

        jBCad_Entregas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBCad_Entregas.setText("Cadastro de Entregas");
        jBCad_Entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCad_EntregasActionPerformed(evt);
            }
        });

        jBRelatorio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBRelatorio.setText("Relatório");
        jBRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRelatorioActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\Logo.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBCad_Entregas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBCad_Programa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBEdiProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBEdiProdutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBProdutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jBPessoas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBProdutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBProduto)
                .addGap(11, 11, 11)
                .addComponent(jBCad_Programa)
                .addGap(12, 12, 12)
                .addComponent(jBCad_Entregas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEdiProdutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBEdiProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBRelatorio)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPessoasActionPerformed
        Cad_Administradores a = new Cad_Administradores();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBPessoasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            this.conexaoSocket = new Socket("127.0.0.1",12345);
            this.Saida = new ObjectOutputStream(conexaoSocket.getOutputStream());
            this.Entrada = new ObjectInputStream(conexaoSocket.getInputStream());
        } catch (IOException ex) {
        System.out.println( "Deu erro na conexao ao servidor."+ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProdutoActionPerformed
        // TODO add your handling code here:
        Cad_Produtos p = new Cad_Produtos();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBProdutoActionPerformed

    private void jBProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProdutorActionPerformed
        // TODO add your handling code here:
        Cad_Produtores pr = new Cad_Produtores ();
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBProdutorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Edi_Administradores adm = new Edi_Administradores();
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBEdiProdutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEdiProdutoresActionPerformed
        Edi_Produtores pro = new Edi_Produtores();
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBEdiProdutoresActionPerformed

    private void jBEdiProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEdiProdutosActionPerformed
        Edi_Produtos prod = new Edi_Produtos();
        prod.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBEdiProdutosActionPerformed

    private void jBCad_ProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCad_ProgramaActionPerformed
        // TODO add your handling code here:
        Cad_Programa prog = new Cad_Programa();
        prog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBCad_ProgramaActionPerformed

    private void jBCad_EntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCad_EntregasActionPerformed
        // TODO add your handling code here:
        Cad_Entregas ent = new Cad_Entregas();
        ent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBCad_EntregasActionPerformed

    private void jBRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRelatorioActionPerformed
        // TODO add your handling code here:
        Relatorio rel = new Relatorio();
        rel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCad_Entregas;
    private javax.swing.JButton jBCad_Programa;
    private javax.swing.JButton jBEdiProdutores;
    private javax.swing.JButton jBEdiProdutos;
    private javax.swing.JButton jBPessoas;
    private javax.swing.JButton jBProduto;
    private javax.swing.JButton jBProdutor;
    private javax.swing.JButton jBRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    // End of variables declaration//GEN-END:variables
}
